version: "3.8"

services:
    tomcat:
      # image: tomcat:9.0
      build: tomcat/.
      ports:
        - "8080:8080"

    haproxy:
      # image: haproxy:2.4
      build: haproxy/.
      command: haproxy -dD -f /etc/haproxy/haproxy.conf
      depends_on: 
        - tomcat
      ports:
        - "80:80"
        - "443:443"
      sysctls:
        - net.ipv4.ip_unprivileged_port_start=0
